### ISSUE TITLE
Brew installation builds from source

### ISSUE THREAD

**Issue by johananl** [allcloud-io/homebrew-tools#1]
Hi,

Using the current config, running `brew install clisso` triggers a compilation from source.
This is problematic on a few levels:

1. It automatically installs Golang on the target machine, which takes time and space.
1. It takes a long time to complete since `dep ensure` is very slow.
1. It doesn't guarantee consistency.

Can't we have Homebrew install the pre-compiled binary from Github?

**Comment by johananl** [comment]
The main reason I've chosen Go for Clisso and not Python or Java is so that we'll have self-contained binaries which can be used as-is. Forcing the user to install Go just to use Clisso is problematic in my opinion (and could also break the dev environment for some people if they develop in Go and did not mean to upgrade it to the latest version...).

I don't know anything about Homebrew, but it doesn't make sense to me we can't simply use a binary. Can you maybe look at how this is done for `kubectl`? https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubernetes-cli.rb
Are they building k8s from source here...? Not sure.

**Comment by johananl** [comment]
Huh, seems like the do compile it on the target machine.
Then... I guess it would be safer to start committing the vendor directory. Otherwise there is no guarantee the build will work since we are running `dep ensure` every time, which could lead to different results.

**Comment by allcloud-jonathan** [comment]
Yeah, they use bottles if available. Basically these are pre-compiled.

Isn’t dep tracking the exact dependency versions?

As I said, we can definitely look into bottle support. But I’d say let’s gain some traction with brew first.

-- 
 <http://bit.ly/bannerlinktoPRGlobes1>
This message and the information 
contained herein is proprietary and confidential and subject to the 
AllCloud policy statement, you may review it here <https://bit.ly/2Mu90e4>.

**Comment by allcloud-jonathan** [comment]
@johananl guess that can be closed
